[context.production.environment]
    VITE_BASE_API_URL="https://study-hub-back-production.up.railway.app"
    VITE_BASE_RECAPTCHA_SITE_KEY="6LdIvcotAAAAAMfU1z6XdTVbDY0a-CpDLohb5G4T"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200