import type { ICourse } from "./VideoCoursesTypes";

export const videoCoursesMock: ICourse[] = [
  {
    id: 1,
    slug: "react-architecture-lab",
    poster: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1200&q=80",
    name: "React Architecture Lab",
    author: "Emma Warren",
    authorRole: "Staff Frontend Engineer",
    description:
      "Практический курс по построению масштабируемых React-приложений: маршрутизация, разделение ответственности, работа с состоянием, асинхронные сценарии и производительность. Курс построен вокруг реального учебного продукта и показывает, как принимать архитектурные решения без лишней абстракции.",
    shortDescription:
      "Масштабируемый React, feature-based структура и production-подход к UI.",
    reviews_count: 128,
    rating_avg: 4.9,
    language: "en",
    duration: 18,
    lessons_count: 12,
    is_free: false,
    price: 59,
    categories: ["Frontend", "Career"],
    dateAdded: "2026-03-12",
    popularity: 980,
    lessons: [
      {
        id: 11,
        title: "Designing the app shell",
        duration: "14:20",
        preview: "https://www.youtube.com/embed/dGcsHMXbSOA",
        description: "Собираем каркас приложения и разбираем границы модулей.",
      },
      {
        id: 12,
        title: "Routing and feature boundaries",
        duration: "18:10",
        preview: "https://www.youtube.com/embed/j942wKiXFu8",
        description: "Связываем навигацию и фичи без связности между слоями.",
      },
      {
        id: 13,
        title: "Data loading patterns",
        duration: "21:45",
        preview: "https://www.youtube.com/embed/T3Px88x_PsA",
        description: "Паттерны загрузки, SWR и управление состоянием экрана.",
      },
    ],
    reviews: [
      {
        id: 101,
        username: "Aruzhan",
        rating: 5,
        comment: "Сильный курс без воды, особенно полезны блоки про структуру фич.",
        created_at: "2026-04-11",
      },
      {
        id: 102,
        username: "Nikita",
        rating: 4,
        comment: "Хороший темп и понятные примеры, хотелось бы еще блок по тестированию.",
        created_at: "2026-04-21",
      },
    ],
  },
  {
    id: 2,
    slug: "node-api-bootcamp",
    poster: "https://images.unsplash.com/photo-1555949963-aa79dcee981c?auto=format&fit=crop&w=1200&q=80",
    name: "Node API Bootcamp",
    author: "Daniel Brooks",
    authorRole: "Backend Lead",
    description:
      "Полный разбор проектирования API на Node.js: REST-контракты, авторизация, валидация, логирование, обработка ошибок и деплой. Вместо игрушечных примеров вы строите backend для образовательной платформы и проходите через типичные production-компромиссы.",
    shortDescription:
      "REST API на Node.js с авторизацией, логированием и production-практиками.",
    reviews_count: 84,
    rating_avg: 4.7,
    language: "en",
    duration: 22,
    lessons_count: 16,
    is_free: false,
    price: 79,
    categories: ["Backend", "DevOps"],
    dateAdded: "2026-02-18",
    popularity: 870,
    lessons: [
      {
        id: 21,
        title: "Contract-first API design",
        duration: "17:00",
        preview: "https://www.youtube.com/embed/Oe421EPjeBE",
        description: "Формируем API-контракт до начала имплементации.",
      },
      {
        id: 22,
        title: "Auth and permissions",
        duration: "22:30",
        preview: "https://www.youtube.com/embed/2jqok-WgelI",
        description: "JWT, роли и безопасная работа с приватными ресурсами.",
      },
      {
        id: 23,
        title: "Monitoring and deploy flow",
        duration: "19:05",
        preview: "https://www.youtube.com/embed/6g5TiDlFIuc",
        description: "Готовим сервис к релизу и наблюдаемости.",
      },
    ],
    reviews: [
      {
        id: 201,
        username: "Sergey",
        rating: 5,
        comment: "Наконец-то курс, где показаны реальные проблемы API, а не только CRUD.",
        created_at: "2026-03-01",
      },
    ],
  },
  {
    id: 3,
    slug: "frontend-interview-sprint",
    poster: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&w=1200&q=80",
    name: "Frontend Interview Sprint",
    author: "Mira Sadykova",
    authorRole: "Senior Frontend Mentor",
    description:
      "Интенсив для разработчиков, которым нужно быстро привести в порядок фундаментальные знания. Курс охватывает JavaScript, браузерные API, рендеринг, React и разбор типовых системных вопросов на собеседованиях. Каждый модуль заканчивается коротким practical drill.",
    shortDescription:
      "JavaScript, браузер, React и системные вопросы для сильного собеседования.",
    reviews_count: 214,
    rating_avg: 4.8,
    language: "ru",
    duration: 10,
    lessons_count: 9,
    is_free: true,
    price: null,
    categories: ["Frontend", "Career"],
    dateAdded: "2026-04-08",
    popularity: 1120,
    lessons: [
      {
        id: 31,
        title: "How browsers really render",
        duration: "12:40",
        preview: "https://www.youtube.com/embed/SmE4OwHztCc",
        description: "Критический путь рендеринга и то, как это обсуждать на интервью.",
      },
      {
        id: 32,
        title: "Advanced JavaScript drills",
        duration: "16:20",
        preview: "https://www.youtube.com/embed/8aGhZQkoFbQ",
        description: "Разбор задач про замыкания, event loop и this.",
      },
      {
        id: 33,
        title: "React system questions",
        duration: "20:00",
        preview: "https://www.youtube.com/embed/bMknfKXIFA8",
        description: "Объясняем архитектурные решения простым и убедительным языком.",
      },
    ],
    reviews: [
      {
        id: 301,
        username: "Anvar",
        rating: 5,
        comment: "Коротко и по делу. Помог структурировать ответы перед собеседованием.",
        created_at: "2026-04-13",
      },
      {
        id: 302,
        username: "Lena",
        rating: 5,
        comment: "Сильный бесплатный курс, удобно смотреть уроки с телефона.",
        created_at: "2026-04-24",
      },
    ],
  },
  {
    id: 4,
    slug: "python-data-foundations",
    poster: "https://images.unsplash.com/photo-1515879218367-8466d910aaa4?auto=format&fit=crop&w=1200&q=80",
    name: "Python Data Foundations",
    author: "Aibek Tulegenov",
    authorRole: "Data Engineer",
    description:
      "Курс для тех, кто хочет начать путь в data-направлении через понятные Python-практики: работа с таблицами, очистка данных, визуализация и построение reproducible notebooks. Материал построен так, чтобы сразу переносить навыки в рабочие аналитические задачи.",
    shortDescription:
      "Python, pandas и аналитические workflows для старта в data-профиле.",
    reviews_count: 56,
    rating_avg: 4.6,
    language: "ru",
    duration: 14,
    lessons_count: 11,
    is_free: false,
    price: 45,
    categories: ["Data Science"],
    dateAdded: "2026-01-25",
    popularity: 640,
    lessons: [
      {
        id: 41,
        title: "Notebook workflow",
        duration: "10:50",
        preview: "https://www.youtube.com/embed/r-uOLxNrNk8",
        description: "Организуем анализ, чтобы его было не стыдно передать коллеге.",
      },
      {
        id: 42,
        title: "Cleaning noisy datasets",
        duration: "18:35",
        preview: "https://www.youtube.com/embed/vmEHCJofslg",
        description: "Нормализация данных и устранение пропусков.",
      },
      {
        id: 43,
        title: "Explaining results",
        duration: "13:15",
        preview: "https://www.youtube.com/embed/GPVsHOlRBBI",
        description: "Показываем выводы так, чтобы они были полезны бизнесу.",
      },
    ],
    reviews: [],
  },
  {
    id: 5,
    slug: "docker-devops-fast-track",
    poster: "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&w=1200&q=80",
    name: "Docker DevOps Fast Track",
    author: "Alex Kim",
    authorRole: "Platform Engineer",
    description:
      "Компактный курс по контейнеризации и основам DevOps для разработчиков. Вы проходите от локальной сборки Docker-образов до публикации, конфигурации окружений и базового CI. Сильный фокус на том, что реально требуется frontend и backend командам при доставке продукта.",
    shortDescription:
      "Docker, окружения и delivery-пайплайн без лишней теории.",
    reviews_count: 67,
    rating_avg: 4.5,
    language: "en",
    duration: 8,
    lessons_count: 7,
    is_free: true,
    price: null,
    categories: ["DevOps", "Backend"],
    dateAdded: "2026-04-19",
    popularity: 760,
    lessons: [
      {
        id: 51,
        title: "Container basics for product teams",
        duration: "11:05",
        preview: "https://www.youtube.com/embed/fqMOX6JJhGo",
        description: "Понимаем, что именно контейнеризуем и зачем.",
      },
      {
        id: 52,
        title: "Docker compose for local work",
        duration: "15:45",
        preview: "https://www.youtube.com/embed/Qw9zlE3t8Ko",
        description: "Собираем локальную среду для нескольких сервисов.",
      },
      {
        id: 53,
        title: "Shipping with CI",
        duration: "17:10",
        preview: "https://www.youtube.com/embed/1pEwRsjzsCs",
        description: "Автоматизируем сборку и проверку образов.",
      },
    ],
    reviews: [
      {
        id: 501,
        username: "Marat",
        rating: 4,
        comment: "Полезный вводный курс, особенно второй урок про compose.",
        created_at: "2026-04-25",
      },
    ],
  },
  {
    id: 6,
    slug: "swift-ui-mobile-starter",
    poster: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?auto=format&fit=crop&w=1200&q=80",
    name: "SwiftUI Mobile Starter",
    author: "Kamila Yessembayeva",
    authorRole: "iOS Engineer",
    description:
      "Стартовый курс по SwiftUI для разработчиков, которые хотят быстро собрать первое мобильное приложение. Внутри: layout-система, state-driven UI, навигация, работа с сетью и выпуск демо-проекта в портфолио.",
    shortDescription:
      "SwiftUI с упором на первое полноценное приложение и понятный state flow.",
    reviews_count: 39,
    rating_avg: 4.4,
    language: "en",
    duration: 11,
    lessons_count: 8,
    is_free: false,
    price: 49,
    categories: ["Mobile"],
    dateAdded: "2026-03-29",
    popularity: 590,
    lessons: [
      {
        id: 61,
        title: "State-driven screens",
        duration: "13:40",
        preview: "https://www.youtube.com/embed/b1oC7sLIgpI",
        description: "Учимся строить мобильный UI от состояния.",
      },
      {
        id: 62,
        title: "Navigation and data flow",
        duration: "15:25",
        preview: "https://www.youtube.com/embed/F2ojC6TNwws",
        description: "Связываем экраны и передачу данных между ними.",
      },
      {
        id: 63,
        title: "Portfolio app polish",
        duration: "18:10",
        preview: "https://www.youtube.com/embed/1xatbOeC0cs",
        description: "Доводим приложение до уровня, который не стыдно показать.",
      },
    ],
    reviews: [],
  },
];
